//
//  MusicTerm.swift
//  Claveo
//
//  Created by Oliver Tran on 11/20/25.
//
//  Copyright (c) 2025 Oliver Tran

import Foundation

struct MusicTerm: Identifiable, Codable, Hashable, Sendable {
    var id: String { term + category }
    let term: String
    let definition: String
    let category: String
    let example: String?
    let symbol: String? // Optional musical symbol (SMuFL character)
    let smuflCode: String? // Optional SMuFL code
    
    enum CodingKeys: String, CodingKey {
        case term, definition, category, example, symbol, smuflCode
    }

    /// Category keys stay English in JSON for filtering; this is the UI label.
    var localizedCategory: String {
        switch category {
        case "Tempo": return String(localized: "Tempo")
        case "Dynamics": return String(localized: "Dynamics")
        case "Articulation": return String(localized: "Articulation")
        case "Ornamentation": return String(localized: "Ornamentation")
        case "Expression": return String(localized: "Expression")
        case "Rhythm": return String(localized: "Rhythm")
        case "Theory": return String(localized: "Theory")
        case "Notation": return String(localized: "Notation")
        case "Form": return String(localized: "Form")
        case "Performance": return String(localized: "Performance")
        case "General": return String(localized: "General")
        case "Instruments": return String(localized: "Instruments")
        default: return category
        }
    }
}

struct MusicSymbol: Identifiable, Codable, Hashable {
    // Use UUID for unique IDs to avoid duplicates
    let id = UUID()
    let symbol: String
    let unicode: String
    let name: String
    let category: String
    let description: String
    let smuflCode: String? // SMuFL code in format "U+E050" (optional for backward compatibility)
    
    enum CodingKeys: String, CodingKey {
        case symbol, unicode, name, category, description, smuflCode
        // Note: id is not in CodingKeys since it's auto-generated
    }
    
    // Custom decoder to handle missing smuflCode field and auto-generate id
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        symbol = try container.decode(String.self, forKey: .symbol)
        unicode = try container.decode(String.self, forKey: .unicode)
        name = try container.decode(String.self, forKey: .name)
        category = try container.decode(String.self, forKey: .category)
        description = try container.decode(String.self, forKey: .description)
        smuflCode = try container.decodeIfPresent(String.self, forKey: .smuflCode)
        // id is automatically generated by UUID()
    }
}

struct MusicDictionary: Codable, Sendable {
    let terms: [MusicTerm]
}

