//
//  MusicTerm.swift
//  Claveo
//
//  Created by Oliver Tran on 11/20/25.
//

import Foundation

struct MusicTerm: Identifiable, Codable, Hashable {
    var id: String { term + category }
    let term: String
    let definition: String
    let category: String
    let example: String?
    
    enum CodingKeys: String, CodingKey {
        case term, definition, category, example
    }
}

struct MusicSymbol: Identifiable, Codable, Hashable {
    // Use UUID for unique IDs to avoid duplicates
    let id = UUID()
    let symbol: String
    let unicode: String
    let name: String
    let category: String
    let description: String
    let smuflCode: String? // SMuFL code in format "U+E050" (optional for backward compatibility)
    
    enum CodingKeys: String, CodingKey {
        case symbol, unicode, name, category, description, smuflCode
        // Note: id is not in CodingKeys since it's auto-generated
    }
    
    // Custom decoder to handle missing smuflCode field and auto-generate id
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        symbol = try container.decode(String.self, forKey: .symbol)
        unicode = try container.decode(String.self, forKey: .unicode)
        name = try container.decode(String.self, forKey: .name)
        category = try container.decode(String.self, forKey: .category)
        description = try container.decode(String.self, forKey: .description)
        smuflCode = try container.decodeIfPresent(String.self, forKey: .smuflCode)
        // id is automatically generated by UUID()
    }
}

struct MusicDictionary: Codable {
    let terms: [MusicTerm]
    let symbols: [MusicSymbol]
}

