backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "index.html"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Full HTML Content", name: "body", widget: "code", default_language: "html", allow_language_selection: false}
